package e.j.a.b.c.n.u;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import com.google.android.gms.common.api.Status;
import e.j.a.b.c.n.k;
import e.j.a.b.c.n.p;
import java.util.concurrent.TimeUnit;

/* loaded from: classes2.dex */
public final class e2<R extends e.j.a.b.c.n.p> extends e.j.a.b.c.n.k<R> {
    private final Status a;

    public e2(Status status) {
        e.j.a.b.c.r.a0.l(status, "Status must not be null");
        e.j.a.b.c.r.a0.b(!status.isSuccess(), "Status must not be success");
        this.a = status;
    }

    @Override // e.j.a.b.c.n.k
    public final void b(@NonNull k.a aVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // e.j.a.b.c.n.k
    @NonNull
    public final R c() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // e.j.a.b.c.n.k
    @NonNull
    public final R d(long j2, @NonNull TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // e.j.a.b.c.n.k
    public final void e() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // e.j.a.b.c.n.k
    public final boolean f() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // e.j.a.b.c.n.k
    public final void g(@NonNull e.j.a.b.c.n.q<? super R> qVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // e.j.a.b.c.n.k
    public final void h(@NonNull e.j.a.b.c.n.q<? super R> qVar, long j2, @NonNull TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // e.j.a.b.c.n.k
    @NonNull
    @e.j.a.b.c.r.d0
    public final <S extends e.j.a.b.c.n.p> e.j.a.b.c.n.t<S> i(@NonNull e.j.a.b.c.n.s<? super R, ? extends S> sVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // e.j.a.b.c.n.k
    @Nullable
    public final Integer j() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @NonNull
    public final Status k() {
        return this.a;
    }
}
